---
# Either specify a host, or automatically use localhost
# $ ansible-playbook -i myhost, <playbook>.yml
# $ ansible-playbook <playbook>.yml
- hosts: "{{ 'all' if ansible_play_hosts | length > 0 else 'localhost' }}"
  connection: "{{ 'ssh' if ansible_play_hosts | length > 0 else 'local' }}"

  tasks:
    - name: Desktop | Install packages
      apt:
        install_recommends: no
        cache_valid_time: 3600
        name:
          - ark
          - filelight
          - fonts-inconsolata
          - gimp
          - gimp-data-extras
          - gimp-dcraw
          - gimp-plugin-registry
          - gimp-texturize
          - gimp-ufraw
          - gnome-disk-utility
          - handbrake
          - imagemagick
          - kde-spectacle
          - kwrite
          - libnss3-tools
          - ocrmypdf
          - okular
          - terminator
          - wireshark
          - xclip
          - xdotool
      become: yes

    - name: Desktop | Create config directories
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      with_items:
        - .config/terminator

    - name: Desktop | Create symlinks for terminator
      file:
        src: "{{ playbook_dir | dirname }}/.config/terminator/config"
        dest: "{{ ansible_env.HOME }}/.config/terminator/config"
        state: link

    - name: Desktop | Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Desktop | Configure XDG user directories
      block:
        - name: Desktop | Create desktop directory
          file:
            path: "{{ ansible_env.HOME }}/.desktop"
            state: directory

        - name: Desktop | Configure XDG user directories
          file:
            src: "{{ playbook_dir | dirname }}/.config/user-dirs.dirs"
            dest: "{{ ansible_env.HOME }}/.config/user-dirs.dirs"
            state: link
            force: yes
          register: _xdg_user_dirs

        - name: Desktop | Confirm deletion of unused XDG user directories
          pause:
            prompt: "Remember to delete unused XDG user directories (~/Templates + ~/Public)"
          when: _xdg_user_dirs.changed

        - name: Desktop | Update configured XDG user directories
          command: xdg-user-dirs-update
          when: _xdg_user_dirs.changed
      when: "'xdg-user-dirs' in ansible_facts.packages"

    # Used for clean shadows on borderldess KDE windows (X11)
    - name: Desktop | Configure Compton
      block:
        - name: Desktop | Fail if trying to install while using Wayland
          fail:
            msg: "Compton only supports X11, not Wayland"
          when: ansible_env.XDG_SESSION_TYPE == "wayland"

        - name: Desktop | Install compton
          apt:
            name: compton
          become: yes

        - name: Desktop | Ensure autostart directory exists
          file:
            path: "{{ ansible_env.HOME }}/.config/autostart"
            state: directory

        - name: Desktop | Configure compton
          file:
            src: "{{ playbook_dir | dirname }}/.config/compton.conf"
            dest: "{{ ansible_env.HOME }}/.config/compton.conf"
            state: link

        - name: Desktop | Add compton to autostart
          file:
            src: "{{ playbook_dir | dirname }}/.config/autostart/compton.desktop"
            dest: "{{ ansible_env.HOME }}/.config/autostart/compton.desktop"
            state: link
          register: _compton_autostart

        - name: Desktop | Disable KDE compositing
          pause:
            prompt: "Make sure KDE compositing is disabled"
          when: _compton_autostart.changed
      when: configure_compton | default('no') | bool

# vim: ft=yaml.ansible
